version: "3.9"

services:
  users_api_dev:
    container_name: "users-api-dev"
    image: "users-api-dev:latest"
    restart: always
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    volumes:
      - .:/usr/src/app
    profiles:
      - development
      - dev
  users_api_prod:
    container_name: "users-api-prod"
    image: "users-api-prod:latest"
    restart: always
    tty: true
    stdin_open: true
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    env_file:
      - ".env"
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    profiles:
      - production
      - prod
